# Generated by Django 3.1.2 on 2020-10-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=2000, null=True)),
                ('experience', models.CharField(blank=True, max_length=600, null=True)),
                ('industry', models.CharField(blank=True, max_length=700, null=True)),
                ('jobdescription', models.CharField(blank=True, max_length=2000, null=True)),
                ('jobid', models.CharField(blank=True, max_length=200, null=True)),
                ('joblocation_address', models.CharField(blank=True, max_length=200, null=True)),
                ('jobtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('numberofpositions', models.CharField(blank=True, max_length=200, null=True)),
                ('payrate', models.CharField(blank=True, max_length=200, null=True)),
                ('postdate', models.CharField(blank=True, max_length=200, null=True)),
                ('site_name', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'job_post',
                'managed': True,
            },
        ),
    ]
